### ISSUE TITLE
Book & Extra Light missing regular typeface

### ISSUE THREAD

**Issue by cheuk879** [silnrsi/font-shimenkan#83] opened 2019-08-26 22:38 UTC
Per build 293 as shown in LO 6.3.0.4 on Windows 10 Pro:
![plrd-test-bold-lo-err-293](https://user-images.githubusercontent.com/10625598/63727883-05e5d300-c81f-11e9-8785-ec7855f9d8b9.png)

The same applies to all other fonts of Shimenkan.  Notice 2 things:
1. The bold typeface is missing for the Book & Extra Light families.
2. The weight of Extra Light is even heavier than Light & the regular family.

Wonder if there's a typo in the build script.  Will need a fix for v1.0.

**Comment by jvgaultney** [comment] 2019-08-28 14:25
I *think* we've got this fixed now. The problem is that to make Windows think that there are four different 'families' with regular & bold (rather than 8 weights of a single family) we have to do some tricks, and our tools were not getting it right. Please retest now with build 295 and let us know if everything is working properly for you.

**Closed as completed** 2019-08-28 20:00 UTC
